// ============================================================
// EDIT THIS FILE TO UPDATE THE TRIP DASHBOARD
// ============================================================

export const tripMeta = {
  title: "Cambodia & Japan 2026",
  subtitle: "June 22 – July 11",
  tagline: "9 people · 20 days · 2 countries · 1 adventure",
  group: [
    { name: "Logan", role: "Organizer", emoji: "★" },
    { name: "Mom", role: "Parent", emoji: "♥" },
    { name: "Dad", role: "Parent", emoji: "♥" },
    { name: "Brother", role: "Sibling", emoji: "◆" },
    { name: "Sister", role: "Sibling (Ghibli fan)", emoji: "◆" },
    { name: "Girlfriend", role: "Partner", emoji: "●" },
    { name: "Brother's GF", role: "Partner", emoji: "●" },
    { name: "Cousin", role: "Family", emoji: "◆" },
    { name: "Japan Grandma", role: "Local guide!", emoji: "★" },
  ],
}

export const cambodiaItinerary = [
  {
    days: "Day 1 — Mon Jun 22",
    location: "Depart LAX",
    icon: "✈",
    color: "blue",
    items: [
      "Depart Los Angeles → Phnom Penh",
      "Long travel day — arrive late night or next morning",
      "Check in, rest up",
    ],
    food: [],
    notes: "Travel day",
  },
  {
    days: "Days 2–4 — Jun 23–25",
    location: "Phnom Penh",
    icon: "🏛",
    color: "red",
    items: [
      "Grandmother visits — anchor of the whole trip",
      "Royal Palace + Silver Pagoda (morning before heat)",
      "Central Market for breakfast baguettes & iced coffee",
      "Tuol Sleng + Choeung Ek (one day if group is ready)",
      "Riverside evening strolls & BBQ stalls",
      "Hire a tuk-tuk for the day (~$15) — skip guided tours",
    ],
    food: ["Kuy teav noodle soup", "Lok lak peppery beef", "Num pang sandwiches", "Fish amok curry"],
    notes: "Move at grandmother's pace. Tuk-tuk driver = full day flexibility.",
  },
  {
    days: "Day 5 — Thu Jun 25",
    location: "Travel to Siem Reap",
    icon: "🚌",
    color: "gold",
    items: [
      "Morning bus (~6h, scenic) OR domestic flight (~45 min, ~$70/person)",
      "Arrive midday — check in, explore Old Market (Psar Chas)",
      "⚠️ Buy 3-day Angkor Pass this afternoon ($62) — avoids 4:30am queue",
      "Evening: Pub Street area for dinner",
    ],
    food: ["Khmer BBQ", "Fresh spring rolls"],
    notes: "Buy Angkor Pass the afternoon before temples. Non-negotiable.",
  },
  {
    days: "Day 6 — Fri Jun 26",
    location: "Angkor — Sunrise + Main Circuit",
    icon: "🌅",
    color: "gold",
    items: [
      "⏰ 4:30am departure from hotel",
      "At gates by 5am — sunrise from the reflection pond",
      "After crowds thin: Angkor Thom, Bayon (giant faces), Ta Prohm",
      "Back by noon — pool, nap, eat",
      "Late afternoon: Tonle Sap floating village by boat",
    ],
    food: ["Hotel breakfast box — order the night before"],
    notes: "June = lush green, far fewer tourists. Rain showers add atmosphere.",
  },
  {
    days: "Day 7 — Sat Jun 27",
    location: "Angkor — Outer Temples",
    icon: "🏯",
    color: "green",
    items: [
      "Start 7:30am — cooler, fewer tourists",
      "Banteay Srei (40km out — pink sandstone, jewel of Angkor)",
      "Afternoon: Phnom Bakheng for sunset views",
      "Easier pace today after yesterday's early start",
    ],
    food: ["Lunch at local market near temples"],
    notes: "Banteay Srei is worth the drive — most tourists skip it.",
  },
  {
    days: "Days 8–9 — Jun 28–29",
    location: "Siem Reap — Slow Days",
    icon: "☕",
    color: "red",
    items: [
      "Angkor National Museum (air-conditioned, great context)",
      "Artisans Angkor workshop — silk & wood carving, no tour vibe",
      "More time with grandmother",
      "Night Market in the evening",
      "One afternoon: just sit somewhere cool with iced drinks",
    ],
    food: ["Fish amok", "Khmer BBQ", "Palm sugar desserts", "Sister Srey Cafe for breakfast"],
    notes: "These buffer days are for grandmother time and recovery.",
  },
  {
    days: "Day 10 — Mon Jun 30",
    location: "Back to Phnom Penh",
    icon: "🏠",
    color: "red",
    items: [
      "Return to Phnom Penh (fly or bus)",
      "Final evening with grandmother",
      "Pack for Japan — early sleep",
      "Flight departs tomorrow at 9pm",
    ],
    food: ["One last Cambodian dinner — make it count"],
    notes: "Vietnam Airlines PNH → KIX departs 9pm July 1.",
  },
  {
    days: "Day 11 — Tue Jul 1",
    location: "Fly to Osaka",
    icon: "✈",
    color: "blue",
    items: [
      "Vietnam Airlines departs 9pm Phnom Penh",
      "1 stop, ~8h40m overnight flight",
      "Arrives Osaka Kansai Airport 6:40am July 2",
      "Try to sleep on the plane — full day ahead on arrival",
    ],
    food: [],
    notes: "PNH → KIX · VN892/VN834 · Booking ref: YG71S02",
  },
]

export const japanItinerary = [
  {
    days: "Days 12–13 — Thu–Fri Jul 2–3",
    location: "Osaka",
    icon: "🌆",
    color: "red",
    nights: "2 nights",
    items: [
      "Land 6:40am — check in early, freshen up, nap in shifts",
      "First mission: konbini breakfast (7-Eleven onigiri is legitimately great)",
      "Dotonbori for street food immersion — takoyaki, kushikatsu",
      "Kuromon Ichiba Market (Osaka's kitchen)",
      "Shinsekai district — old working-class Osaka",
      "Optional day trip: Nara (45 min, free-roaming deer, Todai-ji)",
    ],
    food: ["Takoyaki", "Okonomiyaki", "Kushikatsu", "Konbini onigiri", "Ramen"],
    notes: "Split option: active crew → Nara day trip. Parents → Dotonbori at their pace.",
    transport: "Osaka Metro + walk. Suica card covers everything.",
  },
  {
    days: "Days 14–16 — Sat–Mon Jul 4–6",
    location: "Kyoto",
    icon: "⛩",
    color: "green",
    nights: "3 nights",
    items: [
      "30-min shinkansen from Osaka (¥580/person)",
      "Day 1: Arashiyama bamboo grove at 8am + Tenryu-ji garden",
      "Day 2: Fushimi Inari — HIKE TO SUMMIT (most turn back halfway)",
      "Parents option: lower gates + tea house while crew hikes summit",
      "Philosopher's Path walk between temples",
      "Nishiki Market — Kyoto's kitchen, endless snacking",
      "Day 3: Kurama → Kibune mountain trail + onsen at the end 🥾",
      "Parents: Nishiki Market + Gion + optional tea ceremony",
      "Evening izakayas — Kyoto's are excellent and less rowdy than Tokyo",
    ],
    food: ["Kaiseki dinner (splurge once)", "Yudofu tofu", "Matcha soft serve everywhere", "Nishiki Market snacks"],
    notes: "Kurama–Kibune hike is the highlight — 3-4h through cedar forest, ends at natural hot spring. June hydrangeas are stunning.",
    transport: "¥700/day Kyoto bus pass. Buy at bus terminal outside Kyoto Station.",
    split: {
      parents: "Lower Fushimi gates, tea house, Philosopher's Path, Nishiki Market, optional tea ceremony",
      young: "Full Fushimi summit hike, Kurama–Kibune trail + onsen, evening izakayas",
    },
  },
  {
    days: "Days 17–21 — Tue–Fri Jul 7–10",
    location: "Tokyo",
    icon: "🗼",
    color: "blue",
    nights: "4 nights",
    items: [
      "Shinkansen from Kyoto → Tokyo (~2h40m, ¥13,970/person)",
      "Base: Shinjuku area (young crew) + Ueno area (parents) — 15 min apart",
      "Day 1 night: Golden Gai in Shinjuku — tiny bar alleys, unmissable",
      "Day 2: Ghibli Museum in Mitaka (⚠️ BOOK JUNE 10 AT 10AM JST)",
      "Walk through Inokashira Park to get there",
      "Yanaka neighborhood — old Tokyo streets, local lunch",
      "Tsukiji Outer Market at 7am — best breakfast sushi in the world",
      "Shimokitazawa — vintage shops, live music, local izakayas",
      "Shibuya Crossing evening + Scramble Square observation deck",
      "Isetan Depachika (Shinjuku) — best food basement in the world",
      "Day 4: Senso-ji temple in Asakusa early morning",
      "Final dinner splurge: yakitori omakase or sushi counter",
    ],
    food: ["Ramen (Fuunji for tsukemen)", "Tsukiji sushi breakfast", "Depachika food halls", "Yakitori omakase", "Izakayas in Shimokitazawa"],
    notes: "Japan Grandma is your secret weapon here. Let her lead for restaurants.",
    transport: "Suica card covers all Tokyo Metro + JR Yamanote Line. Google Maps is perfect in Tokyo.",
    split: {
      parents: "Tsukiji morning, Isetan Depachika, Harajuku Omotesando stroll, Meiji Shrine, Ueno Park",
      young: "Golden Gai, Shibuya nightlife, Shimokitazawa bars, Akihabara option",
    },
  },
  {
    days: "Day 21 — Sat Jul 11",
    location: "Fly Home",
    icon: "✈",
    color: "blue",
    nights: "",
    items: [
      "⚠️ Leave hotel by 11am — Narita is 60–90 min from central Tokyo",
      "Keisei Skyliner from Ueno → Narita (36 min, no transfers)",
      "Or N'EX from Shinjuku → Narita (~80 min)",
      "Flight ZG024 departs Narita 14:35",
      "Arrives LAX 8:55am same day",
    ],
    food: ["Quick Tsukiji or konbini breakfast before leaving"],
    notes: "Departs NRT 14:35 · Arrives LAX 08:55 · Flight ZG024",
    transport: "Keisei Skyliner: ¥2,520/person from Keisei-Ueno. Buy day before or at station.",
  },
]

export const transportInfo = [
  {
    title: "Suica Card",
    subtitle: "Everyone needs one — get at Osaka airport on arrival",
    color: "green",
    details: "Tap-and-go card works on every train, subway, and bus in Japan. Also works at convenience stores, vending machines, coin lockers. Load ¥3,000–5,000. Top up at any konbini. One per person.",
    action: "Get Welcome Suica at KIX arrivals hall",
  },
  {
    title: "Skip the JR Pass",
    subtitle: "Individual tickets save ~$2,700 for the group",
    color: "red",
    details: "The JR Pass had a 70% price hike in 2023. For your Osaka→Kyoto→Tokyo route, buying individual tickets is ~¥437,000 cheaper for 9 people. The pass only makes sense for extensive multi-region travel.",
    action: "Buy shinkansen tickets individually at station or on Klook",
  },
  {
    title: "Osaka → Kyoto",
    subtitle: "28 min · JR Special Rapid · ¥580/person",
    color: "gold",
    details: "JR Special Rapid from Osaka → Kyoto Station. Runs every 15 min. Easiest train in Japan. Pay with Suica — no ticket needed.",
    action: "Just tap Suica at the gate",
  },
  {
    title: "Kyoto → Tokyo",
    subtitle: "2h40m · Shinkansen Hikari · ¥13,970/person",
    color: "blue",
    details: "Book reserved seats for 9 people together — do this 2–3 months in advance. Use JR Central English site or Klook. Hikari is 25 min slower than Nozomi but fully covered without surcharge.",
    action: "⚠️ Book reserved seats now — jrcentral.co.jp",
  },
  {
    title: "Getting Around Kyoto",
    subtitle: "¥700/day bus pass · unlimited rides",
    color: "green",
    details: "Kyoto runs on buses more than trains. Buy a ¥700/day bus pass at the bus terminal outside Kyoto Station. Unlimited rides all day. Suica also works on buses.",
    action: "Buy bus pass at Kyoto Station bus terminal",
  },
  {
    title: "Tokyo → Narita Airport",
    subtitle: "Keisei Skyliner · 36 min · ¥2,520/person",
    color: "red",
    details: "From Keisei-Ueno Station → Narita Airport. 36 minutes, no transfers. If staying in Shinjuku: N'EX is ~80 min. Leave hotel by 11am for your 14:35 flight.",
    action: "⚠️ Leave hotel by 11am on July 11",
  },
]

export const bookingChecklist = [
  {
    priority: "urgent",
    item: "Ghibli Museum tickets",
    deadline: "June 10 at 10am JST",
    details: "Lawson Ticket website. 9 people = split into 2 sessions on 2 devices simultaneously. Have all 9 passport numbers ready. Slots: 10am, 12pm, 2pm, 4pm. Sells out in minutes.",
    done: false,
  },
  {
    priority: "urgent",
    item: "Kyoto → Tokyo Shinkansen reserved seats",
    deadline: "Book now — 2–3 months ahead",
    details: "9 reserved seats together on Hikari (not Nozomi). JR Central English site or Klook. Jul 7 departure.",
    done: false,
  },
  {
    priority: "soon",
    item: "Osaka apartment-style accommodation",
    deadline: "Book soon",
    details: "Mimaru Osaka or licensed vacation rental for 9. Near Namba or Shinsaibashi. 2 nights (Jul 2–3).",
    done: false,
  },
  {
    priority: "soon",
    item: "Kyoto apartment-style accommodation",
    deadline: "Book soon",
    details: "Mimaru Kyoto or large apartment near Kyoto Station. 3 nights (Jul 4–6).",
    done: false,
  },
  {
    priority: "soon",
    item: "Tokyo accommodation — dual base",
    deadline: "Book soon",
    details: "Parents: Ueno area (near Keisei Skyliner for Jul 11 airport). Young crew: Shinjuku area. 4 nights (Jul 7–10).",
    done: false,
  },
  {
    priority: "soon",
    item: "Angkor Pass",
    deadline: "Afternoon of Jun 25 (in Siem Reap)",
    details: "3-day pass ($62) at the Angkor Ticket Office. Buy the afternoon before Day 1 of temples. Avoids the 4:30am ticket queue.",
    done: false,
  },
  {
    priority: "prep",
    item: "Suica cards",
    deadline: "Get at Osaka KIX on arrival (Jul 2)",
    details: "Welcome Suica physical card at arrivals hall. iPhone users: Welcome Suica Mobile app. ¥1,500 to start. One per person = 9 cards.",
    done: false,
  },
  {
    priority: "prep",
    item: "Cambodia visas",
    deadline: "Can do online (e-visa) before trip",
    details: "e-visa at evisa.gov.kh — $30 USD, takes 3 business days. Valid 30 days single entry. All non-Cambodian citizens need this.",
    done: false,
  },
]
